AccelHarmonic.cpp
Matrix & AccelHarmonic(Matrix &r, Matrix &E, int n_max, int m_max)
Calcula la aceleración debido a los armónicos esféricos del campo terrestre.
< Parámetros globales y auxiliares Esta función transforma la posición del satélite al sistema de referencia del cuerpo, computa los potenciales asociados a los armónicos esféricos de orden y grado dados, y deriva la aceleración resultante en el sistema inercial. r Vector de posición (3x1) del satélite en coordenadas cartesianas [km]. E Matriz de transformación (de inercial a cuerpo fijo). n_max Orden máximo del desarrollo armónico. m_max Grado máximo del desarrollo armónico. Referencia a una matriz (3x1) con la aceleración resultante [km/s²].
References Cnm, Legendre, Matrix::norm, Snm, transpose.
Referenced by accel, G_AccelHarmonic, varEqn.