R_y.hpp
Matrix & R_y(double angle)
Devuelve la matriz de rotación sobre el eje Y.
angle Ángulo de rotación en radianes. Referencia a una matriz 3x3 que representa la rotación. Devuelve la matriz de rotación sobre el eje Y. angle Ángulo de rotación en radianes. Referencia a una matriz 3x3 correspondiente a la rotación.
References zeros.
Referenced by LTC, PoleMatrix, PrecMatrix.