R_y.cpp
Matrix & R_y(double angle)
Genera la matriz de rotación sobre el eje Y.
Devuelve la matriz de rotación sobre el eje Y. angle Ángulo de rotación en radianes. Referencia a una matriz 3x3 correspondiente a la rotación.
References zeros.
Referenced by LTC, PoleMatrix, PrecMatrix.