Matrix
double** Matrix::data
Puntero a los datos de la matriz.
int Matrix::n_row
Número de filas.
Referenced by AccelPointMass, assign_column, assign_row, dot, extract_column, extract_row, extract_vector, inv, Matrix, Matrix, Matrix, norm, operator(), operator(), operator*, operator*, operator+, operator+, operator-, operator-, operator/, operator/, operator<<, operator=, transpose, union_vector, v_cross.
int Matrix::n_column
Número de columnas.
Referenced by AccelPointMass, assign_column, assign_row, dot, extract_column, extract_row, extract_vector, IERS, inv, Matrix, Matrix, Matrix, norm, operator(), operator(), operator*, operator*, operator+, operator+, operator-, operator-, operator/, operator/, operator<<, operator=, transpose, union_vector, v_cross.
Matrix::Matrix()
Constructor por defecto.
References n_column, n_row.
Referenced by assign_column, assign_row, dot, extract_column, extract_row, extract_vector, inv, operator*, operator*, operator+, operator+, operator-, operator-, operator/, operator/, operator<<, operator=.
Matrix::Matrix(const int v_size)
Constructor para vectores columna.
Constructor de matriz cuadrada (v_size x v_size). v_size Tamaño del vector/cuadrado.
References n_column, n_row.
Matrix::Matrix(const int n_row, const int n_column)
Constructor con dimensiones.
Constructor con número de filas y columnas especificado. n_row Número de filas. n_column Número de columnas.
References n_column, n_row.
double & Matrix::operator()(const int n)
Acceso para vectores.
Accede a un elemento de la matriz usando un único índice. n Índice plano (por filas). Referencia al valor.
References n_column, n_row.
double & Matrix::operator()(const int row, const int column)
Acceso para matrices.
Accede a un elemento usando fila y columna. row Fila (1-based) column Columna (1-based) Referencia al valor.
References n_column, n_row.
Matrix & Matrix::operator+(Matrix &m)
Suma de matrices.
Suma matricial.
References Matrix, n_column, n_row.
Matrix & Matrix::operator+(double s)
Suma escalar.
References Matrix, n_column, n_row.
Matrix & Matrix::operator-(Matrix &m)
Resta de matrices.
Resta matricial.
References Matrix, n_column, n_row.
Matrix & Matrix::operator-(double s)
Resta escalar.
References Matrix, n_column, n_row.
Matrix & Matrix::operator*(Matrix &m)
Multiplicación de matrices.
Producto matricial.
References Matrix, n_column, n_row.
Matrix & Matrix::operator*(double s)
Multiplicación escalar.
Producto escalar por matriz.
References Matrix, n_column, n_row.
Matrix & Matrix::operator/(Matrix &m)
División de matrices (elemento a elemento)
División matricial (multiplicación por inversa).
References inv, Matrix, n_column, n_row.
Matrix & Matrix::operator/(double s)
División escalar.
References Matrix, n_column, n_row.
Matrix & Matrix::operator=(Matrix &m)
Asignación.
Asignación por copia profunda.
References Matrix, n_column, n_row.
double Matrix::norm()
Norma euclídea.
Calcula la norma euclídea.
References n_column, n_row.
Referenced by AccelHarmonic, AccelPointMass, angl, elements, Geodetic.
double Matrix::dot(Matrix &m)
Producto escalar.
Producto escalar (dot product).
References Matrix, n_column, n_row.
Referenced by angl, AzElPa, elements.
Matrix & Matrix::extract_row(int row)
Extrae una fila como vector fila.
Extrae una fila como matriz (1 x n).
References Matrix, n_column, n_row.
Referenced by LTC.
Matrix & Matrix::extract_column(int column)
Extrae una columna como vector columna.
Extrae una columna como matriz (n x 1).
References Matrix, n_column, n_row.
Referenced by DEInteg, IERS.
void Matrix::assign_row(int row, Matrix &v)
Asigna una fila.
Asigna valores a una fila desde un vector.
References Matrix, n_column, n_row.
Referenced by LTC.
void Matrix::assign_column(int column, Matrix &v)
Asigna una columna.
Asigna valores a una columna desde un vector.
References Matrix, n_column, n_row.
Referenced by G_AccelHarmonic, varEqn.
Matrix & Matrix::extract_vector(int from, int to)
Extrae un subconjunto como vector.
Extrae un vector desde un valor hasta otro.
References Matrix, n_column, n_row.
Referenced by accel, elements, JPL_Eph_DE430, varEqn.
Matrix & Matrix::inv()
Inversa de matriz (solo cuadradas)
Calcula la inversa de una matriz.
References eye, inv, Matrix, n_column, n_row.
Referenced by inv, operator/.
ostream & operator<<(ostream &o, Matrix &m)
Sobrecarga de << para imprimir matrices.
o Flujo de salida m Matriz a imprimir Referencia al flujo de salida
References Matrix, n_column, n_row.