matrix.hpp
ostream & operator<<(ostream &o, Matrix &m)
Sobrecarga de << para imprimir matrices.
o Flujo de salida m Matriz a imprimir Referencia al flujo de salida
Matrix & zeros(const int n_row, const int n_column)
Genera una matriz de ceros.
n_row Filas n_column Columnas Matriz llena de ceros Genera una matriz de ceros.
Referenced by _temp, AzElPa, Cheb3D, DE430Coeff, DEInteg, eop19620101, G_AccelHarmonic, GGM03S, Legendre, Position, R_x, R_y, R_z, varEqn.
Matrix & zeros(const int n)
Genera un vector columna de ceros.
n Tamaño del vector Vector de ceros Genera un vector columna de ceros.
Matrix & eye(const int n)
Genera una matriz identidad.
n Tamaño de la matriz cuadrada Matriz identidad Genera una matriz identidad.
Referenced by Matrix::inv, MeasUpdate.
Matrix & transpose(Matrix &m)
Calcula la transpuesta de una matriz.
m Matriz a transponer Matriz transpuesta Calcula la transpuesta de una matriz.
References Matrix::n_column, Matrix::n_row.
Referenced by accel, AccelHarmonic, DEInteg, elements, MeasUpdate, TimeUpdate, varEqn.
Matrix & union_vector(Matrix &v1, Matrix &v2)
Une dos vectores columna en uno solo.
v1 Primer vector v2 Segundo vector Vector concatenado Une dos vectores columna en uno solo.
References Matrix::n_column, Matrix::n_row.
Referenced by accel, JPL_Eph_DE430.
Matrix & v_cross(Matrix &v, Matrix &w)
Calcula el producto vectorial entre dos vectores 3D.
v Primer vector w Segundo vector Producto vectorial Calcula el producto vectorial entre dos vectores 3D.
References Matrix::n_column, Matrix::n_row.
Referenced by elements.