matrix.cpp
ostream & operator<<(ostream &o, Matrix &m)
Sobrecarga de << para imprimir matrices.
o Flujo de salida m Matriz a imprimir Referencia al flujo de salida
Matrix & zeros(const int n_row, const int n_column)
Crea una matriz de ceros.
Genera una matriz de ceros.
Referenced by _temp, AzElPa, Cheb3D, DE430Coeff, DEInteg, eop19620101, G_AccelHarmonic, GGM03S, Legendre, Position, R_x, R_y, R_z, varEqn.
Matrix & zeros(const int n)
Crea una matriz cuadrada de ceros.
Genera un vector columna de ceros.
Matrix & eye(const int n)
Crea una matriz identidad.
Genera una matriz identidad.
Referenced by Matrix::inv, MeasUpdate.
Matrix & transpose(Matrix &m)
Devuelve la transpuesta de una matriz.
Calcula la transpuesta de una matriz.
References Matrix::n_column, Matrix::n_row.
Referenced by accel, AccelHarmonic, DEInteg, elements, MeasUpdate, TimeUpdate, varEqn.
Matrix & v_cross(Matrix &v, Matrix &w)
Producto vectorial entre dos vectores 3D.
Calcula el producto vectorial entre dos vectores 3D.
References Matrix::n_column, Matrix::n_row.
Referenced by elements.
Matrix & union_vector(Matrix &v1, Matrix &v2)
Concatena dos vectores.
Une dos vectores columna en uno solo.
References Matrix::n_column, Matrix::n_row.
Referenced by accel, JPL_Eph_DE430.